"""Monolix adapter — a real external engine via ``lixoftConnectors`` in R.

Ported from the PopPK Workbench's Monolix tab. Monolix 2024R1's connector
library is x86_64-only on this Mac, so the fit runs in an isolated Intel R
(``~/.monolix-mamba/envs/monolixR``) under Rosetta with a stray
``DYLD_LIBRARY_PATH`` stripped — exactly what ``poppk-shiny/monolix/run-monolix.sh``
does, reproduced here in Python so the app has no shell dependency.

Structural models are generated as mlxtran text with the ``pkmodel`` macro
(never guessed Monolix library identifiers); the R side (``r/monolix_fit.R``)
builds the project, sets the observation error model / distribution, runs SAEM
+ standard errors + log-likelihood, and writes ``results.csv`` / ``status.json``
/ ``loglik.json``. Estimates are mapped back to the app's parameter names and
scored through the same ``score_from_population`` as every other engine.

``available()`` is a cheap file check (isolated Rscript + MonolixSuite present);
the engine additionally needs a logged-in macOS GUI session (WindowServer) —
from a headless shell it hangs, which the fit timeout turns into a ``failed``
row rather than a stuck job.

Environment overrides: ``PHARMAGENT_MONOLIX_SUITE`` (monolixSuite path),
``PHARMAGENT_MONOLIX_RSCRIPT`` (the x86_64 Rscript), ``PHARMAGENT_MONOLIX_TIMEOUT``.
"""
from __future__ import annotations

import csv
import json
import math
import os
import platform
import shutil
import subprocess
import tempfile
import time
from pathlib import Path
from typing import Any

from .base import CandidateSpec, EngineResult
from .dataset_io import _COLUMNS, write_nonmem_csv
from .scoring import score_from_population

DEFAULT_SUITE = "/Applications/MonolixSuite2024R1.app/Contents/Resources/monolixSuite"
DEFAULT_RSCRIPT = "~/.monolix-mamba/envs/monolixR/bin/Rscript"
R_SCRIPT = Path(__file__).resolve().parent / "r" / "monolix_fit.R"
_FIT_TIMEOUT_S = float(os.environ.get("PHARMAGENT_MONOLIX_TIMEOUT", "900"))

# app model key -> Monolix pkmodel() argument list (also the estimated names).
# Only structures whose parameters map 1:1 onto the app's names are exposed.
_PKMODEL: dict[str, list[str]] = {
    "iv_1cmt": ["V", "Cl"],
    "iv_2cmt": ["Cl", "V1", "Q", "V2"],
    "iv_3cmt": ["Cl", "V1", "Q2", "V2", "Q3", "V3"],
    "oral_1cmt": ["ka", "V", "Cl"],
    "oral_1cmt_lag": ["Tlag", "ka", "V", "Cl"],
    "oral_2cmt": ["ka", "Cl", "V1", "Q", "V2"],
}
_TO_APP = {"Cl": "CL", "ka": "KA", "Tlag": "TLAG", "V": "V", "V1": "V1", "V2": "V2", "V3": "V3",
           "Q": "Q", "Q2": "Q2", "Q3": "Q3"}
_ERROR_MODEL = {"proportional": "proportional", "additive": "constant", "constant": "constant",
                "combined": "combined1", "combined1": "combined1", "combined2": "combined2"}
# NONMEM-style columns written by dataset_io -> Monolix header types
_HEADER_TYPES = {"ID": "id", "TIME": "time", "DV": "observation", "AMT": "amount",
                 "EVID": "evid", "CMT": "ignore", "WT": "contcov"}


def mlxtran_model(model_key: str) -> str:
    """mlxtran structural model for a key (pkmodel macro; Cc is the output)."""
    pars = _PKMODEL[model_key]
    return (f"DESCRIPTION: {model_key} (generated by PharmAgent)\n\n"
            "[LONGITUDINAL]\n"
            f"input = {{{', '.join(pars)}}}\n\n"
            "EQUATION:\n"
            f"Cc = pkmodel({', '.join(pars)})\n\n"
            "OUTPUT:\n"
            "output = Cc\n")


def header_types() -> list[str]:
    return [_HEADER_TYPES[c] for c in _COLUMNS]


def omega_sd_to_cv_pct(sd: float) -> float:
    """Log-normal individual parameters: CV% = 100·sqrt(exp(ω²) − 1)."""
    return 100.0 * math.sqrt(math.exp(sd * sd) - 1.0)


def parse_results(rows: list[dict[str, str]], model_key: str) -> dict[str, Any]:
    """results.csv (parameter, estimate, RSE_pct) -> theta / omega CV% / sigma."""
    theta: dict[str, float] = {}
    rse: dict[str, float | None] = {}
    omega_cv: dict[str, float] = {}
    sigma: dict[str, float | None] = {"prop": None, "add": None}
    for r in rows:
        name = r["parameter"]
        try:
            est = float(r["estimate"])
        except (TypeError, ValueError):
            continue
        rse_v = None
        try:
            rse_v = float(r.get("RSE_pct", "")) if r.get("RSE_pct") not in (None, "", "NA") else None
        except ValueError:
            rse_v = None
        if name.endswith("_pop"):
            base = name[:-4]
            app = _TO_APP.get(base)
            if app:
                theta[app] = est
                rse[app] = rse_v
        elif name.startswith("omega_"):
            app = _TO_APP.get(name[6:])
            if app:
                omega_cv[app] = omega_sd_to_cv_pct(est)
        elif name == "a":
            sigma["add"] = est
        elif name == "b":
            sigma["prop"] = est
    expected = {_TO_APP[p] for p in _PKMODEL[model_key]}
    missing = sorted(expected - set(theta))
    return {"theta": theta, "rse_pct": rse, "omega_cv_pct": omega_cv, "sigma": sigma,
            "missing": missing}


def _rscript() -> Path:
    return Path(os.path.expanduser(os.environ.get("PHARMAGENT_MONOLIX_RSCRIPT", DEFAULT_RSCRIPT)))


def _suite() -> Path:
    return Path(os.environ.get("PHARMAGENT_MONOLIX_SUITE", DEFAULT_SUITE))


def _command(rscript: Path, config: str) -> list[str]:
    """``arch -x86_64`` forces Rosetta on Apple silicon (the connector lib is Intel-only)."""
    cmd = [str(rscript), str(R_SCRIPT), config]
    if platform.system() == "Darwin" and platform.machine() == "arm64" and shutil.which("arch"):
        cmd = ["arch", "-x86_64", *cmd]
    return cmd


def _env() -> dict[str, str]:
    env = dict(os.environ)
    env.pop("DYLD_LIBRARY_PATH", None)   # an anaconda lib path shadows the Monolix Qt libs
    return env


class MonolixAdapter:
    name = "monolix"

    def available(self) -> bool:
        return _rscript().is_file() and _suite().exists() and R_SCRIPT.is_file()

    def fit(self, spec: CandidateSpec, subjects: list[dict], *,
            seed: int = 20250614) -> EngineResult:
        if spec.model_key not in _PKMODEL:
            return EngineResult(engine=self.name, model_name=spec.model_key, status="failed",
                                message=f"monolix adapter supports {sorted(_PKMODEL)}")
        from app.compute.pk_models import get_model

        model = get_model(spec.model_key)
        error_model = _ERROR_MODEL.get(spec.error_model.lower(), "proportional")
        t0 = time.perf_counter()
        with tempfile.TemporaryDirectory(prefix="monolix_") as tmp:
            data = write_nonmem_csv(subjects, os.path.join(tmp, "data.csv"), is_iv=model.is_iv)
            model_file = os.path.join(tmp, f"model_{spec.model_key}.txt")
            Path(model_file).write_text(mlxtran_model(spec.model_key))
            out_dir = os.path.join(tmp, "out")
            os.makedirs(out_dir, exist_ok=True)
            config = os.path.join(tmp, "config.json")
            Path(config).write_text(json.dumps({
                "suite": str(_suite()), "dataFile": data, "headerTypes": header_types(),
                "modelFile": model_file, "errorModel": error_model,
                "distribution": "lognormal", "outDir": out_dir, "seed": seed}))
            try:
                proc = subprocess.run(_command(_rscript(), config), capture_output=True, text=True,
                                      timeout=_FIT_TIMEOUT_S, env=_env())
            except subprocess.TimeoutExpired:
                return EngineResult(engine=self.name, model_name=spec.model_key, status="failed",
                                    message=("monolix fit timed out — the engine needs a logged-in "
                                             "GUI session (run the app from Terminal/RStudio)"))
            status_path = os.path.join(out_dir, "status.json")
            if not os.path.exists(status_path):
                tail = (proc.stderr or proc.stdout or "")[-400:]
                return EngineResult(engine=self.name, model_name=spec.model_key, status="failed",
                                    message=f"monolix produced no status: {tail}")
            status = json.loads(Path(status_path).read_text())
            if not status.get("ok"):
                return EngineResult(engine=self.name, model_name=spec.model_key, status="failed",
                                    message=str(status.get("message", "monolix fit failed"))[:400])
            with open(os.path.join(out_dir, "results.csv"), newline="") as fh:
                rows = list(csv.DictReader(fh))
            loglik: dict[str, Any] = {}
            ll_path = os.path.join(out_dir, "loglik.json")
            if os.path.exists(ll_path):
                try:
                    loglik = json.loads(Path(ll_path).read_text())
                except ValueError:
                    loglik = {}
        dt = time.perf_counter() - t0

        parsed = parse_results(rows, spec.model_key)
        if parsed["missing"]:
            return EngineResult(engine=self.name, model_name=spec.model_key, status="failed",
                                message=f"monolix results missing {parsed['missing']}")
        theta, omega_cv, sigma = parsed["theta"], parsed["omega_cv_pct"], parsed["sigma"]
        iiv = [p for p in (spec.iiv_params or list(omega_cv)) if p in omega_cv] or list(omega_cv)
        app_error = "combined" if (sigma["prop"] and sigma["add"]) else \
            ("additive" if sigma["add"] and not sigma["prop"] else "proportional")
        sc = score_from_population(spec.model_key, subjects, theta=theta, omega_cv_pct=omega_cv,
                                   sigma_prop=sigma["prop"], sigma_add=sigma["add"],
                                   iiv_params=iiv, error_model=app_error)
        ofv = None
        for key in ("-2LL", "OFV", "-2 x log-likelihood"):
            if isinstance(loglik.get(key), (int, float)):
                ofv = float(loglik[key])
                break
        return EngineResult(
            engine="monolix_saem", engine_version="MonolixSuite2024R1", model_name=spec.model_key,
            converged=True, runtime_s=dt, ofv=ofv,   # within-engine only (Monolix scale)
            params=theta, rse_pct=parsed["rse_pct"], omega_cv_pct=omega_cv, sigma=sigma,
            iiv_params=iiv, error_model=app_error, n_subjects=len(subjects),
            raw={"results": rows, "loglik": loglik, "status": status}, **sc,
        )
